version: '2.3'

services:

  starwars:
    image: starwars
    container_name: starwars
    working_dir: /data
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - PYTHONPATH=/data
    volumes:
      - ../:/data
    runtime: nvidia
    command: tail /dev/null -f
  tensorboard:
    image: tensorflow/tensorflow
    container_name: tensorboard
    working_dir: /logs
    ports:
     - "6006:6006"
    volumes:
      - ../src/rl/tensorboard:/logs
    command: tensorboard --logdir /logs
